/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as IndexRouteImport } from './routes/index'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/entities': typeof EntitiesRoute
  '/graph': typeof GraphRoute
  '/sources': typeof SourcesRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/entities': typeof EntitiesRoute
  '/graph': typeof GraphRoute
  '/sources': typeof SourcesRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conflicts': typeof ConflictsRoute
  '/entities': typeof EntitiesRoute
  '/graph': typeof GraphRoute
  '/sources': typeof SourcesRoute
  '/vocabulary': typeof VocabularyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conflicts'
    | '/entities'
    | '/graph'
    | '/sources'
    | '/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conflicts' | '/entities' | '/graph' | '/sources' | '/vocabulary'
  id:
    | '__root__'
    | '/'
    | '/conflicts'
    | '/entities'
    | '/graph'
    | '/sources'
    | '/vocabulary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConflictsRoute: typeof ConflictsRoute
  EntitiesRoute: typeof EntitiesRoute
  GraphRoute: typeof GraphRoute
  SourcesRoute: typeof SourcesRoute
  VocabularyRoute: typeof VocabularyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConflictsRoute: ConflictsRoute,
  EntitiesRoute: EntitiesRoute,
  GraphRoute: GraphRoute,
  SourcesRoute: SourcesRoute,
  VocabularyRoute: VocabularyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
